version: '3.9'
services:
  backend:
    image: reserva-backend
    build: back/.
    ports:
      - "8081:8081"
    expose:
      - "8081"
    command: mvn spring-boot:run
    networks:
      - hvu-networks
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://backend-db:5432/reserva-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
  
  reserva-db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: reserva-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    expose:
      - "5432"
    networks:
      - hvu-networks
    volumes:
      - pg-data:/var/lib/postgresql/data
