spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reserva?useTimezone=true&serverTimezone=UTC
    username: root
    password: Info@1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
